base_url = "https://beta.gruvw.com"

compile_sass = true
minify_html = true
build_search_index = false # TODO search box

default_language = "en"

[search]
include_title = true
include_description = false
include_content = true

[markdown]
highlight_code = true

[extra]
title = "Gruvw" # website pages title and subtitle suffix
email = "gruvw.dev@gmail.com" # contact email
github = "gruvw" # GitHub username
