name: Build and Deploy Zola Website on GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-only:
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build only
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: src
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: src
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
